### ISSUE TITLE
[Bug] Dead "Bürgermeister" has to call a new one even if the game is over.

### ISSUE THREAD

**Issue by Joshix-1** [foin137/werwolfonline.eu#15]
Wenn der Bürgermeister stirbt und das Spiel zuende geht, bevor er einen Nachfolger bestimmen konnte, kann ein neues Spiel erst gestartet werden, wenn der Bürgermeister einen Nachfolger ernennt.

**Comment by foin137** [comment]
Danke, sollte nun gefixed sein
