### ISSUE TITLE
The "Hexe" can kill her-/himself after (s)he got killed by the "Werwölfe"

### ISSUE THREAD

**Issue by Joshix-1** [foin137/werwolfonline.eu#17]
![image](https://user-images.githubusercontent.com/57299889/93687852-80842f00-fac1-11ea-9031-853cba9bfb73.png)

**Comment by foin137** [comment]
Well ... I think about everything in the night happening simultaneously, so I don't see a problem, if the "Hexe" poisons herself and the werewolves kill her as well,

what do you think should be the correct behaviour?

**Comment by Joshix-1** [comment]
I probably just would log onxe that the Hexe died. The two log messages are confusing. So I would just send one. 
The Hexe is just stupid if she kills the one she could heal, so I wouldn't stop her from doing so.

**Comment by foin137** [comment]
Fixed this duplicate log entry!
