### ISSUE TITLE
Indicate which players have to react

### ISSUE THREAD

**Issue by dsmic** [foin137/werwolfonline.eu#21]
We tried to play werwolf from Homeoffice keeping a Audioconference parallel.

We were about 25 players (online christmas party) and the problem was, that it was not possible to figure out, which player is holding the game.

Would it be possible to display a list of players to all players, for which we are waiting?

#22

**Comment by foin137** [comment]
Yeah that's a good idea, one should, however, be careful that we do not give away too much information this way - but this can easily be fixed by a simple timer
