### ISSUE TITLE
Liebespaar bekommt nichts angezeigt

### ISSUE THREAD

**Issue by ollimaz** [foin137/werwolfonline.eu#25]
Ich bin mehrmals auf das Problem gestoßen, dass das ein Mitglied des Liebespaares nichts angezeigt bekommt! 

Reproduce:
Amor wählt sich selbst und jemand anderen 
Man selbst bekommt es angezeigt, der Partner bekommt keinen Screen angezeigt, dass er verliebt ist. Ob es durch andere Wahl auch Möglich ist, ist mir nicht bekannt.

**Comment by foin137** [comment]
Kann ich leider nicht reproducen, bei mir bekommen beide etwas angezeigt, außerdem ist es ja auch noch im player log vermerkt.

**Comment by ollimaz** [comment]
Ich komischerweise auch nicht mehr. Kann erstmal geschlossen werden. Sofern ich es reproduzieren kann werde ich das Ticket erneut öffnen.

**Comment by ollimaz** [comment]
Der Fehler liegt nicht am PC sondern an dem Nutzern ... diese haben den Infotext für das Liebespaar mit einer normalen Info Nachricht in der Nacht verwechselt und ohne es zu lesen auf weiterschlafen geklickt. 
Behoben hab ich es indem ich die Buttonfarbe geändert hab. Ist vlt eine neue Idee?
