### ISSUE TITLE
Spiel blockiert nachdem ein Spieler entfernt wurde.

### ISSUE THREAD

**Issue by jotoeri** [foin137/werwolfonline.eu#26]
Uns ist eine Person in der Phase der Werwöfe abhanden gekommen, sie konnte entsprechend auch nicht mehr das weiterschlafen bestätigen. Wir haben nur noch auf diese Person gewartet, alle anderen hatten schon bestätigt.
Der Moderator hat daraufhin die Person aus dem Spiel entfernt, was aber dazu geführt hat, dass wir im Warte-Zustand gefangen waren. Hinter dem Warten-auf Text stand zwar kein Name mehr, das Spiel ging aber leider auch nicht mehr voran.

**Comment by foin137** [comment]
Das ist ungut, sollte jetzt aber gefixt sein

**Comment by jotoeri** [comment]
Super, danke! :)
