### ISSUE TITLE
Problems with PHP 8.1 or newer

### ISSUE THREAD

**Issue by MrSmoer** [foin137/werwolfonline.eu#33]
Erstmal vielen Dank für das schöne Spiel ;-)
ich habe letztens versucht das Spiel bei mir selbst auszuführen und hatte immer Fehler mit MYSQLI nach ein wenig googlen bin ich auf dashier gestoßen: [PHP 8.1: MySQLi: Default error mode set to exceptions](https://php.watch/versions/8.1/mysqli-error-mode)
Anscheinend werden seit php 8.1 Fehler bei MYSQL-Verbindungen standardmäßig als "Exception" betrachtet und nicht mehr als "silent error". Das führt zu Problemen mit php 8.1. 
Es scheint auch eine konfigurationsoption beim Herstellen der Verbindung geben, mit der man das alte Verhalten wiederherstellen kann (ich glaube im Artikel relativ weit unten).

Viele Grüße!

**Comment by foin137** [comment]
Danke für die Info und vor allem auch fürs Herausfinden des Fehlers!
Bei mir läuft es jetzt wieder.
Das ist natürlich unschön, wenn so ein backwards-compatibility break eingeführt wird. Andererseits war das error handling wohl auch nicht gut umgesetzt im Code.
Es sollte jetzt wieder funktionieren
